# docker-compose.test.yml   â† only the pieces that differ
version: "3.9"

services:
  db_test:
    image: postgres:15
    environment:
      POSTGRES_DB: weather_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alwayssunny
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-test:
    build: .
    restart: always
    depends_on:
      - db_test
    environment:
      NODE_ENV: docker_test
      # local
      DATABASE_URL: postgres://postgres:alwayssunny@db_test:5432/weather_db_test

      WEATHER_API_KEY: 588e4679207f459c9d893949251405
      RESEND_API_KEY: re_D4x576dB_Cp74P9pQKpvuUwjqGyEEHeUo
      FROM_EMAIL: skyfetch@resend.dev
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm start

  test-e2e:
    build:
      context: .
      dockerfile: Dockerfile.test-e2e
    depends_on:
      - db_test
      - backend-test
    environment:
      NODE_ENV: docker_test
      DATABASE_URL: postgres://postgres:alwayssunny@db_test:5432/weather_db_test
    command: >
      sh -c "npx sequelize-cli db:migrate --env docker_test &&
             npm run test-docker:e2e"

  test-integration:
    build: .
    depends_on:
      - db_test
    entrypoint: [ "/bin/sh", "-c", "npx sequelize-cli db:migrate --env docker_test && npm run test-docker:integration" ]
    environment:
      NODE_ENV: docker_test
      DATABASE_URL_TEST: postgres://postgres:alwayssunny@db_test:5432/weather_db_test
